### PR TITLE
feat: add rpoplpush command

### PR DESCRIPTION
**Pull request by LhdDream**
Related to https://github.com/flower-corp/rosedb/issues/180.

Add tests
Add server command
Please review when you have time.

### CODE REVIEW

**Comment by roseduan** [comment]
Thanks for your PR.

I reviewed the redis docs of the command, seems that this command is regarded as deprecated.
https://redis.io/commands/rpoplpush/

You can review the `LMove` method to check whether it can be replaced by it. If not, you can make some changes.

**Comment by LhdDream** [comment]
ok

**Comment by roseduan** [comment]
Any updates? @LhdDream

**Comment by gozeloglu** [comment]
I think, there is no need to add `RPOPLPUSH` cmd. It is deprecated and `LMOVE` can be used instead of it.

**Pull request closed without merging**
