### PR TITLE
Add LIndex command

### PR DESCRIPTION
**Pull request by icemint0828**
* Test cases added.

Related to #123

### CODE REVIEW

**Comment by roseduan** [comment]
review @icemint0828

**Comment by icemint0828** [comment]
@roseduan
Fix conflicts, please check.

**Comment by icemint0828** [comment]
Hi, @roseduan.
Sorry, is there something wrong with my PR?

**Comment by icemint0828** [comment]
Hi, @roseduan. 
If you have time, may I ask you to check the code?
If something is wrong with me, I would like to correct it.
I am not sure what is going on because there has been no movement for a long time.

**Comment by roseduan** [comment]
sorry, a little busy before

**Comment by icemint0828** [comment]
It's ok!
Thanks for your review.

**Pull request merged**
