### PR TITLE
Add Decr, DecrBy, Incr, IncrBy commands

### PR DESCRIPTION
**Pull request by gozeloglu**
[`Decr`](https://redis.io/commands/decr/), [`DecrBy`](https://redis.io/commands/decrby/), [`Incr`](https://redis.io/commands/incr/), [`IncrBy`](https://redis.io/commands/incrby/) methods added. 
* New error types added.
* General-purpose helper method added.

Signed-off-by: Gökhan Özeloğlu <gozeloglu@gmail.com>

### CODE REVIEW

**Comment by roseduan** [comment]
fix conflicts @gozeloglu

**Comment by gozeloglu** [comment]
> fix conflicts @gozeloglu

Conflicts are fixed @roseduan.

**Comment by gozeloglu** [comment]
Hi @roseduan. A kind ping. Could you review this PR when you have time?

**Comment by gozeloglu** [comment]
There is a bug in the code. I am fixing it. Not merge for right now.

**Comment by gozeloglu** [comment]
Hi, @roseduan again. I think the PR seems ready to review. Lastly, I added `Incr` and `IncrBy` commands. I had already written a general-purpose helper method for incrementing and decrementing keys. I just refactored the code with small touches(updating integer overflow part, method name, signature, value update, etc.). The only branch name is not appropriate for `Incr` and `IncrBy` commands because I started this PR for adding `Decr` and `DecrBy` commands. But, I think it's not so critical and important. I am here to make changes if it's needed after your review.

**Comment by roseduan** [comment]
> Hi, @roseduan again. I think the PR seems ready to review. Lastly, I added `Incr` and `IncrBy` commands. I had already written a general-purpose helper method for incrementing and decrementing keys. I just refactored the code with small touches(updating integer overflow part, method name, signature, value update, etc.). The only branch name is not appropriate for `Incr` and `IncrBy` commands because I started this PR for adding `Decr` and `DecrBy` commands. But, I think it's not so critical and important. I am here to make changes if it's needed after your review.

thanks for your great work!

**Pull request merged**
